# Lets consider predicting sequence using LSTM
[10, 20, 30, 40, 50, 60, 70, 80, 90]

### Data Prep -  Initializing X and Y

In [1]:
import numpy as np

In [2]:
# Initialize an array 'x' 6 rows * 3 columns
x = np.empty([6,3])
print (x)

[[4.65915686e-310 0.00000000e+000 1.78057652e-306]
 [5.01089494e-292 2.50643943e-292 1.53108789e-308]
 [5.01051268e-292 1.07056303e-296 1.45368568e-291]
 [2.13579715e-287 2.21874561e-296 5.50929518e-279]
 [5.98123966e-154 1.96086579e+243 1.45913393e-152]
 [2.43194431e-152 5.38151221e+228 5.53194614e+199]]


In [3]:
# Add the data sequence in array x
a = 10
m = 1
for i in range(len(x)):
    n = a * m
    for j in range(3):
        x[i][j] = n
        n += 10
    m += 1
    
print (x)

[[10. 20. 30.]
 [20. 30. 40.]
 [30. 40. 50.]
 [40. 50. 60.]
 [50. 60. 70.]
 [60. 70. 80.]]


In [4]:
# Initialize array for y (labels) 6 rows * 1 cols
y = np.empty([6,1])
print (y)

[[4.65915704e-310]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]
 [0.00000000e+000]]


In [5]:
# Assign labels in y
n = 40
for i in range(len(y)):
    y[i] = n
    n += 10

print (y)

[[40.]
 [50.]
 [60.]
 [70.]
 [80.]
 [90.]]


In [10]:
x.shape, y.shape

((6, 3), (6, 1))

### Define LSTM

In [8]:
#Import modules
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [14]:
#Define input feature
n_steps = 3              #number of time steps - [10 20 30] = [40]
n_features = 1            #Univariate - hence only one feature

In [16]:
#Define model
model = Sequential()
model.add(LSTM(units=50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

## Train the model

In [22]:
#We have multiple samples, hence model will expect input data to have dimension as
#[n_samples, n_steps, n_features]
#In our case we have 
# n_samples: 6
# n_steps: 3
# n_features: 1

In [23]:
#Input shape
x.shape

(6, 3)

In [24]:
#Need to re-shape as (6, 3, 1)
X = x.reshape((x.shape[0], x.shape[1], n_features))
X.shape

(6, 3, 1)

In [25]:
# Fit model
model.fit(X, y, epochs=256, verbose=1)

Epoch 1/256
1/1 [==============================] - 0s 1ms/step - loss: 4585.9331
Epoch 2/256
1/1 [==============================] - 0s 1ms/step - loss: 4557.9282
Epoch 3/256
1/1 [==============================] - 0s 1ms/step - loss: 4530.1060
Epoch 4/256
1/1 [==============================] - 0s 3ms/step - loss: 4502.4263
Epoch 5/256
1/1 [==============================] - 0s 1ms/step - loss: 4474.8462
Epoch 6/256
1/1 [==============================] - 0s 833us/step - loss: 4447.3223
Epoch 7/256
1/1 [==============================] - 0s 935us/step - loss: 4419.8032
Epoch 8/256
1/1 [==============================] - 0s 844us/step - loss: 4392.2383
Epoch 9/256
1/1 [==============================] - 0s 896us/step - loss: 4364.5688
Epoch 10/256
1/1 [==============================] - 0s 1ms/step - loss: 4336.7368
Epoch 11/256
1/1 [==============================] - 0s 1ms/step - loss: 4308.6802
Epoch 12/256
1/1 [==============================] - 0s 1ms/step - loss: 4280.3335
Epoch 13/256
1/1 

1/1 [==============================] - 0s 1ms/step - loss: 13.7534
Epoch 102/256
1/1 [==============================] - 0s 1ms/step - loss: 13.0137
Epoch 103/256
1/1 [==============================] - 0s 858us/step - loss: 12.3510
Epoch 104/256
1/1 [==============================] - 0s 1ms/step - loss: 11.7181
Epoch 105/256
1/1 [==============================] - 0s 1ms/step - loss: 11.0868
Epoch 106/256
1/1 [==============================] - 0s 1ms/step - loss: 10.4490
Epoch 107/256
1/1 [==============================] - 0s 996us/step - loss: 9.8141
Epoch 108/256
1/1 [==============================] - 0s 1ms/step - loss: 9.2036
Epoch 109/256
1/1 [==============================] - 0s 2ms/step - loss: 8.6442
Epoch 110/256
1/1 [==============================] - 0s 2ms/step - loss: 8.1595
Epoch 111/256
1/1 [==============================] - 0s 2ms/step - loss: 7.7621
Epoch 112/256
1/1 [==============================] - 0s 2ms/step - loss: 7.4492
Epoch 113/256
1/1 [=========================

1/1 [==============================] - 0s 3ms/step - loss: 0.9456
Epoch 204/256
1/1 [==============================] - 0s 3ms/step - loss: 0.9323
Epoch 205/256
1/1 [==============================] - 0s 3ms/step - loss: 0.9193
Epoch 206/256
1/1 [==============================] - 0s 3ms/step - loss: 0.9065
Epoch 207/256
1/1 [==============================] - 0s 3ms/step - loss: 0.8941
Epoch 208/256
1/1 [==============================] - 0s 5ms/step - loss: 0.8820
Epoch 209/256
1/1 [==============================] - 0s 2ms/step - loss: 0.8702
Epoch 210/256
1/1 [==============================] - 0s 2ms/step - loss: 0.8586
Epoch 211/256
1/1 [==============================] - 0s 961us/step - loss: 0.8474
Epoch 212/256
1/1 [==============================] - 0s 1ms/step - loss: 0.8364
Epoch 213/256
1/1 [==============================] - 0s 988us/step - loss: 0.8257
Epoch 214/256
1/1 [==============================] - 0s 961us/step - loss: 0.8152
Epoch 215/256
1/1 [=============================

## Test Model
Test sequence: [70, 80 ,90] = [100]

In [27]:
#Initialize test array
x_test = np.array([70, 80, 90])
x_test

array([70, 80, 90])

In [28]:
#Reshape test input
X_test = x_test.reshape(1, n_steps, n_features)
X_test.shape

(1, 3, 1)

In [29]:
#Predict output
yhat = model.predict(X_test, verbose=1)

1/1 [==============================] - 0s 954us/step


In [30]:
print (yhat)

[[102.360085]]
